version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_DB=django_dev
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    ports:
      - "5433:5432"
  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
volumes:
  pgdata: