# Generated by Django 4.0.4 on 2022-06-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
