# Generated by Django 4.0.4 on 2022-06-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
