# Generated by Django 4.0.4 on 2022-06-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='AUTRE', max_length=100),
        ),
    ]
