# Generated by Django 4.0.4 on 2022-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
