# Generated by Django 4.0.4 on 2022-06-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
